#debug: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hq_test
    username: "root"
    password: "root"
    druid:
      stat-view-servlet:
        login-username: druid
        login-password: druid
        enabled: true
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      max-wait: 3000
      filters: stat, wall, logback


  mail:
    username: mail@qq.com
    password: 123456
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
